### ISSUE TITLE
Music and Sounds

### ISSUE THREAD

**Issue by crimsonshade** [crimsonshade/magic-rush#32]
### Description
I have to find some sounds. One or two tracks as a background music, and a few sound effects for dying and shooting etc.

### ToDo
- [ ] Music
     - [ ] Find / Create a background music
- [ ] Sound Effects
     - [ ] Shooting sound
     - [ ] Player dying sound
     - [ ] troll dead sound? `// maybe? but maybe to much`
     - [ ] coin collect sound

### Ideas
First try to look in the asset store, if I find something fitting. Otherwise, try using some free software to create some sounds or music.
